defaults:
    - algo: sac

num_train_steps: 1000000
fifo_buffer_capacity: 3e5
mh_buffer_capacity: 10

exploration:
    num_init_explr: 20
    num_periodic_explr: 0

eval_granularity: 10000
device: cuda
seed: 254
env_name: T1DSimEnv
